config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  # clarify route to About page
  get 'about', to: 'pages#about'

  #resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  # removing 'only' because (a) all methods are exposed and (b) exposes RESTful transfers
  resources :articles

  # redirect route for signup to the new method
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 256}
end

app/models/user.rb
class User < ApplicationRecord
  before_save {
    self.email = email.downcase
  }

  has_many :articles

  validates :username,
    presence: true,
    uniqueness: {case_sensitive: false},
    length: {minimum: 3, maximum: 25}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email,
    presence: true,
    uniqueness: {case_sensitive: false},
    length: {maximum: 105},
    format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
    #obviated by before_action    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def new
    # Essentially declaring a variable for the .html.erb file
    @article = Article.new
  end

  def edit
    #obviated by before_action    @article = Article.find(params[:id])
  end

  def create
    # params.require(:article) means that 'article' must appear in the parameters list for it to work
    # permit(:title, :description) means that only title and description will be set upon creation
    @article = Article.new(strong_parameters)

    # Temporary fix until proper solution has been written:
    @article.user = User.first

    if @article.save
      flash[:notice] = "Article has been saved"
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    #obviated by before_action    @article = Article.find(params[:id])

    if @article.update(strong_parameters)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    #obviated by before_action    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def strong_parameters 
    params.require(:article).permit(:title, :description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def edit
    # already set in before_action
  end

  def create
    @user = User.new(strong_parameters)

    if @user.save
      flash[:notice] = "Congratulations, #{@user.username}, you are now signed up for Alpha Blog!"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def update
    if @user.update(strong_parameters)
      flash[:notice] = "#{@user.username}, your record has been updated."
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  private

  def strong_parameters 
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
  
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control", placeholder: "Article title" %>
          </div>
        </div>
  
        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Article description" %>
          </div>
        </div>
  
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light bg-success" %>
          <%= link_to "Cancel", articles_path, class: "btn btn-outline-light bg-danger" %>
        </div>
      <% end %>
  
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles</h1>

<center>
  <div class="container">
      <% @articles.each do |article| %>
        <div class="row">
          <div class="col-12 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded" style="width: 18rem;">
              <div class="card-header font-italic">
                by <%= article.user.username %>
              </div>
              <div class="card-body">
                <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-info" %></h5>
                <p class="card-text"><%= truncate(article.description, length: 100) %></p>
                <%= link_to 'Show', article_path(article), class: "btn btn-info"  %>
                <%= link_to 'Edit', edit_article_path(article), class: "btn btn-success" %>
                <%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
                <div class="card-footer text-muted small">
                  Created <%= time_ago_in_words(article.created_at) %> ago.  Last edited <%= time_ago_in_words(article.updated_at) %> ago.
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</center>

<p>
  <%= link_to 'Create new article', new_article_path %> |
  <%= link_to 'Home', root_path %>
</p>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center mt-4">Article details</h1>

<div class="row justify-content-md-center">
  <div class="card text-center shadow mb-5 bg-white rounded" style="width: 18rem;">
    <div class="card-header font-italic">
      by <%= @article.user.username %>
    </div>

    <div class="card-body">
      <h5 class="card-title">
        <%= simple_format(@article.title) %>
      </h5>

      <div class="card-text text-left">
        <%= simple_format(@article.description) %>
      </div>
  
      <!-- Buttons -->
      <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-success" %>
      <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
    </div>

    <div class="card-footer text-muted small">
      Created <%= time_ago_in_words(@article.created_at) %> ago.  Last edited <%= time_ago_in_words(@article.updated_at) %> ago.
    </div>

    <%= link_to 'Return to listing', articles_path, class: "btn btn-info" %>

  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Mark F. Rogers", "https://www.cs.colostate.edu/~mfrogers/", class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_main_image.html.erb
<!-- Text box in middle -->
<div class="container">
    <div class="jumbotron">
      <p class="lead">A trivial application exercise from a novice-level Rails course.</p>
      <p>The original is over-engineered for such a trivial application.  We want the UI as simple as possible.</p>
        <hr class="my-4">
        <p><i>Note: the jury's still out about whether the course is much good.  So far it's a superficial treatment of the subject.</i></p>
        <a class="btn btn-primary btn-lg" href="#" role="button">See articles</a>
    </div>
</div>

app/views/layouts/_messages.html.erb
<% if flash.any? %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <% flash.each do |name, msg| %>
      <%= msg %>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <!-- Items on the navigation bar -->
    <ul class="navbar-nav mr-auto">

      <!-- Articles dropdown -->
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
          <%= link_to "Article listing", articles_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
        </div>
      </li>

      <!-- About link -->
      <li class="nav-item">
        <%= link_to "About", about_path, class: "nav-link" %>
      </li>
    </ul>

    <!-- (unused) search bar -->
    <!--
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Alpha Blog</h1>
<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<!-- Text box in middle -->
<div class="container" id="home-container">
  <div class="jumbotron text-center text-white" >
    <h1>Alpha Blog</h1>
    <p class="lead">A trivial application exercise from a novice-level Rails course.</p>
    <p>The original is over-engineered for such a trivial application.  We want the UI as simple as possible.</p>
    <hr class="my-4">
    <p><i>Note: the jury's still out about whether the course is much good.  So far it's a superficial treatment of the subject.</i></p>
    <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4>The following errors occurred.</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
  
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control", placeholder: "Enter name" %>
          </div>
        </div>
  
        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.email_field :email, class: "form-control", placeholder: "Enter a valid email address" %>
          </div>
        </div>
  
        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control", placeholder: "Choose a password" %>
          </div>
        </div>
  
        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update", class: "btn btn-outline-light bg-success") %>
          <%= link_to "Cancel", users_path, class: "btn btn-outline-light bg-danger" %>
        </div>
      <% end %>
  
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form' %>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha Blog</h1>
<%= render 'form' %>